# Generated by Django 3.1.1 on 2020-09-09 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=100, verbose_name='Текст статті')),
                ('image', models.ImageField(blank=True, upload_to='post/', verbose_name='Зображення')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Створенно')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновленно')),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерація')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'db_table': 'post',
                'ordering': ['create'],
            },
        ),
    ]
